accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    
    path('signup',views.signup , name='signup' ),
    path('profile/<slug:slug>',views.profile , name='profile' ),
    path('log-out/',views.logout_view , name='customLogout' ),



] 

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    
    path('',views.all_product , name='store'),
    path('autosearch',views.autoSearch , name='autosearch'),
    path( '<slug:slug>', views.product_detail , name='product_detail'),
    path('cart/',views.cart , name='cart'),
    
    # login to checkout
    # path('login-to-checkout/', views.checkout_login_page, name="checkout_login"),
    path('log-out/',views.logout_view , name='customLogout' ),

    # sign up to checkout
    # path('signup-to-checkout/', views.checkout_signup_page, name="checkout_signup"),
    # path('user-data/', views.get_login_data, name="login_data"),

    path('checkout/',views.checkout , name='checkout'),
    path('likeItem/', views.likeItem, name="likeItem"),
    path('favorites/', views.liked_product, name="liked_product"),
    path('process_order/', views.processOrder, name="process_order"),
    # ajax func urls
    path('addToCartWithAjax/', views.addToCartWithAjax, name="addToCartWithAjax"),
    path('cartInfo/', views.cartInfo, name="cartInfo"),
    
    
] 

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # path('accounts/', include('django.contrib.auth.urls')),
    
    # path('accounts/', include('accounts.urls' , namespace='accounts')),

    path('products/', include('product.urls' , namespace='products')),

] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/forms.py
from django import forms
from django.contrib.auth import authenticate

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def check_login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user
    
    

product/views.py
# from django.http.response import HttpResponse
# from django.http.response import HttpResponse, HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import render , get_object_or_404, redirect
from .models import Product, Order, OrderItem, ShippingAddress
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
import datetime
from .utils import CartData
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import login, logout
from .forms import LoginForm




def logout_view(request):
    print("************log out*************")
    response = redirect(reverse('products:store'))
    response.delete_cookie("cart")
    logout(request)
    return response
    
def all_product(request):
    search_qs = request.GET.get('searchname', '')
    if search_qs:
        products = Product.objects.filter(name__icontains=search_qs)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 100) 
    pages = request.GET.get('page')
    products = paginator.get_page(pages)

    data = CartData(request)
    cartItems = data['cartItems']
    context = {'products' : products, 'cartItems': cartItems,}
    return render(request , 'product/store.html' , context)




def product_detail(request , slug):
    product = get_object_or_404(Product ,PRDSLug=slug )
    data = CartData(request)
    cartItems = data['cartItems']

    context = {'product' : product, 'cartItems': cartItems,}
    return render(request , 'product/detail.html' , context)




def cart(request):
    data = CartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    # if request.user.is_authenticated:
    #     customer = request.user.customer
    #     order, created = Order.objects.get_or_create(customer=customer, complete=False)
    #     items = order.orderitem_set.all()
    #     cartItems = order.get_cart_items
    # else:
    #     mycart = json.loads(request.COOKIES['cart'])
    #     order = {'get_cart_total':0, 'get_cart_items':0, 'shipping': False}
    #     cartItems = order['get_cart_items']
    #     items = []
    #     for i in mycart:
    #         try:
    #             cartItems += mycart[i]['quantity']
    #             product = Product.objects.get(id = i)
    #             total = (product.price * mycart[i]['quantity'])
    #             order['get_cart_total'] +=total 
    #             order['get_cart_items'] +=mycart[i]['quantity']
    #             item = {
    #                 'product':{
    #                     'id':product.id,
    #                     'name':product.name,
    #                     'price':product.price,
    #                     'imageURL':product.imageURL,
    #                     'PRDSLug':product.PRDSLug,
    #                 },
    #                 'quantity':mycart[i]['quantity'],
    #                 'get_total': total,
    #             }
    #             items.append(item)
    #             if product.digital ==False:
    #                 order['shipping']=True
    #         except:
    #             pass
        
    return render(request, 'product/cart.html', {'items':items, 'order': order, 'cartItems': cartItems})
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

 
def checkout_signup_page(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            if user:
                order, created = Order.objects.get_or_create(customer=user.customer, complete=False)
                cart = json.loads(request.COOKIES['cart'])
                if cart:
                    for line in cart:
                        product = Product.objects.get(id = line)
                        # check if the product in the user order's line or not
                        found = OrderItem.objects.filter(order=order, product=product).count()
                        if found:
                            orderitem = OrderItem.objects.get(order=order, product=product)
                            orderitem.quantity += cart[line]["quantity"]
                            orderitem.save()
                        else:
                            orderitem = OrderItem.objects.create(order=order, product=product)
                            orderitem.quantity = cart[line]["quantity"]
                            orderitem.save()

            login(request, user)   
            response = redirect(reverse('products:store'))
            response.delete_cookie("cart")
            return response

    else:
        form = UserCreationForm()

    context = {'form' : form}
    return render(request , 'product/check_signup.html' , context)


def checkout_login_page(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        #check_login return ==> user
        user = form.check_login(request)
        if user:
            order, created = Order.objects.get_or_create(customer=user.customer, complete=False)
            cart = json.loads(request.COOKIES['cart'])
            if cart:
                for line in cart:
                    product = Product.objects.get(id = line)
                    # check if the product in the user order's line or not
                    found = OrderItem.objects.filter(order=order, product=product).count()
                    if found:
                        orderitem = OrderItem.objects.get(order=order, product=product)
                        orderitem.quantity += cart[line]["quantity"]
                        orderitem.save()
                    else:
                        orderitem = OrderItem.objects.create(order=order, product=product)
                        orderitem.quantity = cart[line]["quantity"]
                        orderitem.save()

            login(request, user)
        
            response = redirect(reverse('products:store'))
            response.delete_cookie("cart")
            return response
    
    return render(request, 'product/check_login.html', {'login_form': form })


@login_required(login_url="/products/login-to-checkout/")
def checkout(request):
    data = CartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    return render(request, 'product/checkout.html', {'items':items, 'order': order, 'cartItems': cartItems})



def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    if order.shipping == True:
        ShippingAddress.objects.create(
        customer=customer,
        order=order,
        address=data['shipping']['address'],
        city=data['shipping']['city'],
        state=data['shipping']['state'],
        zipcode=data['shipping']['zipcode'],
        )

    order.complete = True
    order.save()    

    return JsonResponse('payment complete', safe=False)  
    


@login_required
def liked_product(request):
    customer = request.user.customer
    products = Product.objects.filter(like=customer)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    cartItems = order.get_cart_items

    return render(request, 'product/favorit.html', {'products':products, 'cartItems': cartItems})


def autoSearch(request):
    q_original = request.GET.get('term')
    qs = Product.objects.filter(name__icontains = q_original)
    if qs:
        names = []
        names+=[x.name for x in qs]
    else:
        names = ['No results']
    return JsonResponse(names, safe=False)


    
def addToCartWithAjax(request):
    if request.user.is_authenticated:
        product_id = request.GET.get("productId")
        action = request.GET.get("action")
        customer = request.user.customer
        product = Product.objects.get(id=product_id)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        objs_founded = OrderItem.objects.filter(order=order,product=product).count()
        if objs_founded:
            orderItem = OrderItem.objects.get(order=order,product=product)
            if action == "add":
                orderItem.quantity += 1
                orderItem.save()
            elif action == "remove" and orderItem.quantity > 1:
                orderItem.quantity -= 1
                orderItem.save()
            elif action == "delete":
                orderItem.delete()    
        else:
            orderItem = OrderItem.objects.create(order=order, product=product, quantity = 1)
            orderItem.save()
        data = {
        "cartQty": order.get_cart_items,  
            "productQty":orderItem.quantity,
            "line_price":orderItem.get_total,
            "cart_total":order.get_cart_total,
        }
    else:
        mycart = json.loads(request.COOKIES['cart'])
        order = {'get_cart_total':0, 'get_cart_items':0, 'shipping': False}
        cartItems = order['get_cart_items']
        items = []
        for i in mycart:
            try:
                cartItems += mycart[i]['quantity']
                product = Product.objects.get(id = i)
                total = (product.price * mycart[i]['quantity'])
                order['get_cart_total'] +=total 
                order['get_cart_items'] +=mycart[i]['quantity']
                item = {
                    'product':{
                        'id':int(product.id),
                        'name':f'{product.name}',
                        'price':float(product.price),
                        'imageURL':f'{product.imageURL}',
                        'PRDSLug':f'{product.PRDSLug}',
                    },
                    'quantity':int(mycart[i]['quantity']),
                    'get_total': int(total),

product/templates/product/cart.html
{% extends 'product/main.html' %}
{% load static %}
{% block body %}
<div class="container mt-5 mb-5" style="margin-top:129px !important">
	<div class="row">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
<div class="col-lg-12">
			<div class="cart_info box-element">
				
				<a  class="btn btn-outline-dark mb-3" href="{% url 'products:store' %}">&#x2190; Continue Shopping</a>

				<table class="table">
					<tr>
						<th><h5>Items: <strong class="cart_items"></strong></h5></th>
						<th><h5>Total:<strong class="cart_total"></strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-outline-dark" href="{% url 'products:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			
			
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
					<div style="flex:1"><strong></strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row cart-row{{item.product.id}}">
					<div style="flex:2"><img class="thumbnails" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p><a href="{% url 'products:product_detail' item.product.PRDSLug  %}">{{item.product.name}}</a></p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity"><span class="qty{{item.product.id}}">{{item.quantity}}</span></p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-qty" src="{% static  'img/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-qty" src="{% static  'img/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p class="line_price{{item.product.id}}">${{item.get_total|floatformat:2}}</p></div>
					<!-- <button data-product="{{item.product.id}}" data-action="delete" class="update-cart"><i class="fas fa-trash-alt mr-5"></i></button> -->
					<div style="flex:1"><button data-product="{{item.product.id}}" data-action="delete" 
							class="btn btn-sm btn-outline-danger update-qty">
							<i class="fa fa-trash"></i> 
							Trash
						</button>
					</div>
				</div>			
				{% endfor %}
			<div class="col-sm-12 empty-cart-cls text-center" style="display:none"> <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
				<h3><strong>Your Cart is Empty</strong></h3>
				<h4>Add something to make me happy :)</h4> <a href="{% url 'products:store' %}" class="btn btn-outline-dark cart-btn-transform m-3" data-abc="true">continue shopping</a>
			</div>	
				

			</div>
		</div>
		</div>
		</div>
{% endblock body %}
{% block javascript %}
<script>

	function addCookieItem(productId, action){
	  if(action=='add'){
		if(cart[productId]==undefined){
		  cart[productId] = {'quantity':1}
		}else{
		  cart[productId]['quantity'] +=1
		}
	
	  }
	
	  else if(action=='remove' && cart[productId]['quantity'] >1 ){
		  cart[productId]['quantity'] -=1
	  }

	  else if(action=='delete'){
		delete cart[productId]	
		
	  }
	
	  console.log('Cart:', cart)
	  document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
	  // location.reload()
	
	
	}
	
	//cart functionality inside the the cart page 
	var updateBtns = document.querySelectorAll('.update-qty')
	for(i=0;i<updateBtns.length;i++){
	  updateBtns[i].addEventListener('click', function(e){
		var p_id = this.dataset.product,
		action=this.dataset.action,
		product_name=this.dataset.name;
		if(user == 'AnonymousUser'){
		  addCookieItem(p_id, action);
		  $.ajax({
			url: "{% url 'products:addToCartWithAjax' %}",
			dataType:'json',
			data: {
			  mycart:JSON.stringify(cart),
			},
			success: function(data){
				//data["cartQty"]
				//data["items"]
				
				$("#cart-total , .cart_items").text(data["cartQty"])
				var items = JSON.parse(data["items"])				
					items.forEach((ele)=>{

							if(ele["product"]["id"] === +p_id){
								$(".qty" + p_id).text(ele["quantity"])
								$(".line_price" + p_id).text("$" + ele["get_total"])
							}
							 

							
					})
					if(action==="delete"){
						$(".cart-row" + p_id).css("display","none")
						if(items.length === 0){
							$(".cart-row").css("display","none");
							$(".cart_info ").css("display","none");
							$(".empty-cart-cls").css("display","block");
						}
						
					}
					

					$(".cart_total").text("$" + data["cart_total"])
				  
				  
				


			
			 
			}
		  })
		  
		}
		else{
			  $.ajax({
				url: "{% url 'products:addToCartWithAjax' %}",
				dataType:'json',
				data: {
				  productId:p_id,
				  action:action,
				},
				success: function(data){
				  
					$("#cart-total , .cart_items").text(data["cartQty"])
					if(action == "add"){
					  $(".qty" + p_id).text(data["productQty"])
					  $(".line_price" + p_id).text("$" + data["line_price"])
					  $(".cart_total").text("$" + data["cart_total"])
					}else if(action == "remove" && data["productQty"] >= 1){
						$(".qty" + p_id).text(data["productQty"])
						$(".line_price" + p_id).text("$" + data["line_price"])
						$(".cart_total").text("$" + data["cart_total"])
					  }else if(action == "delete"){
						$(".cart-row" + p_id).remove()
						$(".cart_total").text("$" + data["cart_total"])
						if(data["cartQty"] == 0){
						  $(".empty-cart-cls").css("display","block")
						  $(".cart_info").css("display","none")
						  $(".cart-row").css("display","none")
						}}
					

				  
				}
			  })
			}


	  })
	}
 
  </script>


<!-- <script>
      
	var updateBtns = document.querySelectorAll('.update-qty')
	
	for(i=0;i<updateBtns.length;i++){
	  
	  updateBtns[i].addEventListener('click', function(e){
		var p_id = this.dataset.product
		var action=this.dataset.action
		$.ajax({
		  url: "{% url 'products:addToCartWithAjax' %}",
		  dataType:'json',
		  data: {
			productId:p_id,
			action:action,
		  },
		  success: function(data){
			$("#cart-total , .cart_items").text(data["cartQty"])
			if(action == "add"){
			  $(".qty" + p_id).text(data["productQty"])
			  $(".line_price" + p_id).text("$" + data["line_price"])
			  $(".cart_total").text("$" + data["cart_total"])
			}
			else if(action == "remove" && data["productQty"] >= 1){
			  $(".qty" + p_id).text(data["productQty"])
			  $(".line_price" + p_id).text("$" + data["line_price"])
			  $(".cart_total").text("$" + data["cart_total"])
			}
			else if(action == "delete"){
			  $(".cart-row" + p_id).remove()
			  $(".cart_total").text("$" + data["cart_total"])
			  if(data["cartQty"] == 0){
				$(".empty-cart-cls").css("display","block")
				$(".cart_info").css("display","none")
				$(".cart-row").css("display","none")
			  }
			}

		  }
		})
  
	  })

	}
  </script>
   -->
{% endblock %}

product/templates/product/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript">
      var user = '{{request.user}}'
    </script>
    <title>souq</title>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary" style="position:fixed;top:0;right:0;left:0;z-index:1000">
      <a class="navbar-brand text-light" href="{% url 'products:store' %}">Souq Store</a>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

        </ul>
        <a href="{% url 'products:liked_product' %}">
        <button data-product="{{product.id}}" data-action="add"
        class="btn btn-info mr-3 like-product">
        <i class="fas fa-heart"></i> 
        </button>
        </a>

        <form class="form-inline my-2 my-lg-0" action="{% url 'products:store' %}">
          <input id="searchId" name="searchname" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
        </form>
        
        <ul class="navbar-nav">
          
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <strong class="text-light">{{ user.username }}</strong>

            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% comment %} <a class="dropdown-item" href="{% url 'accounts:profile' user.customer %}">View Profil</a> {% endcomment %}
              <a class="dropdown-item" href="#">Edit Profil</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">My Orders</a>
              <a class="dropdown-item" href="#">Track My Order</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Change Password</a>
            </div>
          </li>
          <li class="nav-item mt-2 ml-5">
            <strong><a class="text-light" href="{% url 'products:customLogout' %}">Logout</a></strong>
          </li>
          {% else %}
          <li class="nav-item mt-2 ml-5">
            <strong ><a class="text-light" href="{% url 'account_login' %}">Login</a></strong>
          </li>
          
        {% endif %}


            <li class="nav-item active mt-1">
              
              <div class="form-inline my-2 my-lg-0">
                <a href="{% url 'products:cart' %}">
                  <img  id="cart-icon" src="{% static 'img/cart.png' %}">
                </a>
                {% comment %} <p id="cart-total"></p> {% endcomment %}
                <p id="cart-total"></p>
              </div>
          </li>
        </ul>
      </div>
    </nav>
<div class="smg" style="
visibility: hidden;
background: #0fa70f;
width: 100%;
height: 44px;
margin-top: -68px;
position: fixed;
z-index: 1000;
color:white;
text-align:center;
line-height: 42px;
font-size: 20px;
word-spacing: 5px;

"></div>



  {% block body  %}
    
 


  {% endblock body %}


    <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% comment %} <script src="{% static 'js/cart.js' %}"></script> {% endcomment %}
    <script src="{% static 'js/cart_ajax.js' %}"></script>
    {% comment %} <script src="{% static 'js/like.js' %}"></script>    {% endcomment %}
   
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>    
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      $( function() {

        $( "#searchId" ).autocomplete({
          source:"{% url 'products:autosearch' %}",
        });


          $.ajax({
            url: "{% url 'products:cartInfo' %}",
            dataType:'json',
            success: function(data){
  
              $("#cart-total , .cart_items").text(data["cartQty"])
              $(".cart_total").text("$" + data["cart_total"])
              
              if(data["cartQty"] == 0){
                $(".empty-cart-cls").css("display","block")
                $(".cart_info").css("display","none")
                $(".cart-row").css("display","none")          
              }
              if(data["num_liked_products"] == 0){
                $(".empty_liked").css("display","block")  
              }
              
              //make the like btn red
              if(user !="AnonymousUser"){
                for(i=0;i<data["liked_list"].length;i++){
                  $(".likeId" +data["liked_list"][i]).addClass("like")
                }
              }
            }
          })
        })



      </script>

<script type="text/javascript">
      var user = '{{request.user}}'
 
      function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken');
    
    function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}

		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){
			cart = {}
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
    </script>

    <!-- ajax call to add product in cookies -->

    <script>

      function addCookieItem(productId, action){
        if(action=='add'){
          if(cart[productId]==undefined){
            cart[productId] = {'quantity':1}
          }else{
            cart[productId]['quantity'] +=1
          }
      
        }
      
        if(action=='remove'){
          if(cart[productId]['quantity'] >1){
            cart[productId]['quantity'] -=1
          }
          
        }
        if(action=='delete'){
          delete cart[productId]	
          
        }
      
        console.log('Cart:', cart)
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        // location.reload()
      
      
      }
      
    

      var updateBtns = document.querySelectorAll('.update-cart')
      for(i=0;i<updateBtns.length;i++){
        updateBtns[i].addEventListener('click', function(e){
          var p_id = this.dataset.product,
          action=this.dataset.action,
          product_name=this.dataset.name;
          console.log("user from ajax: ", user)
          if(user == 'AnonymousUser'){
            addCookieItem(p_id, action);
            $.ajax({
              url: "{% url 'products:addToCartWithAjax' %}",
              dataType:'json',
              data: {
                mycart:JSON.stringify(cart),
              },
              success: function(data){
                $(".smg").text(product_name + " added to card successfully").css("visibility","visible")
                setTimeout(function(){$(".smg").css("visibility","hidden")},2000);
                $("#cart-total").text(data["cartQty"])
                $(".qty" + p_id).text(data["productQty"])
                var mydata = JSON.parse(data["items"])
                console.log("product id", mydata[0]["product"]["id"])
                console.log("product name", mydata[0]["product"]["name"])
                console.log("product price", mydata[0]["product"]["price"])
                console.log("product imageURL", mydata[0]["product"]["imageURL"])
                console.log("product PRDSLug", mydata[0]["product"]["PRDSLug"])
               //var c = JSON.stringify(data["items"])
              }
            })
            
          }else{
                $.ajax({
                  url: "{% url 'products:addToCartWithAjax' %}",
                  dataType:'json',
                  data: {
                    productId:p_id,
                    action:action,
                  },
                  success: function(data){
                    $(".smg").text(product_name + " added to card successfully").css("visibility","visible")
                    setTimeout(function(){$(".smg").css("visibility","hidden")},2000);
                    $("#cart-total").text(data["cartQty"])
                    $(".qty" + p_id).text(data["productQty"])

                    
                  }
                })
              }


        })
      }
   
    </script>


    
<!-- like product -->
<script>
  var updateBtns = document.querySelectorAll('.like-product')
  for(i=0;i<updateBtns.length;i++){
    updateBtns[i].addEventListener('click', function(e){
      var p_id = this.dataset.product;

      if(user == 'AnonymousUser'){
        window.location.href = "{% url 'account_login' %}"
      }else{
        $.ajax({
          url: "{% url 'products:likeItem' %}",
          dataType:'json',
          data: {
            productId:p_id,
          },
          success: function(data){
            if(data["added"]){
              $(".likeId" + p_id).addClass("like")
              $(".likedNum" + p_id).text(data["liked_num"])
            }else{
                $(".liked_card" + p_id).css("display","none")
                $(".likeId" + p_id).removeClass("like")
                $(".likedNum" + p_id).text(data["liked_num"])
                if(data["num_liked_products"] == 0){
                  $(".empty_liked").css("display","block")
              }
                

              
              
              
            }                
          }
        })
      }
      })
    }

</script>



    {% block javascript %}
  
{% endblock %}
  
  </body>

</html>